// 演示用合成数据，不包含真实主机名、序列号、MAC 或内网地址。
type DemoDeviceInput = {
  hostname: string;
  platform: "Windows" | "darwin";
  osName: string;
  cpu: string;
  memoryBytes: number;
  diskBytes: number;
  ip: string;
  mac: string;
  uuid: string;
};

const buildDeviceData = ({
  hostname,
  platform,
  osName,
  cpu,
  memoryBytes,
  diskBytes,
  ip,
  mac,
  uuid,
}: DemoDeviceInput) =>
  JSON.stringify({
    os: {
      arch: platform === "darwin" ? "arm64" : "x64",
      fqdn: `${hostname}.example.local`,
      uefi: true,
      build: "demo-build",
      distro: osName,
      kernel: "demo-kernel",
      serial: `DEMO-OS-${uuid.slice(-4).toUpperCase()}`,
      release: platform === "darwin" ? "14.0" : "10.0.22621",
      codename: platform === "darwin" ? "macOS Sonoma" : "",
      codepage: "UTF-8",
      hostname,
      logofile: platform === "darwin" ? "darwin" : "windows",
      platform,
      servicepack: "",
    },
    cpu: {
      brand: cpu,
      cache: { l1d: 0, l1i: 0, l2: 1048576, l3: 6291456 },
      cores: 8,
      flags: "",
      model: "",
      speed: 3.2,
      family: "demo",
      socket: "demo",
      vendor: platform === "darwin" ? "Apple" : "GenuineIntel",
      voltage: "",
      governor: "",
      revision: "",
      speedMax: 3.2,
      speedMin: 1.8,
      stepping: "0",
      processors: 1,
      manufacturer: platform === "darwin" ? "Apple" : "Intel",
      physicalCores: 4,
      virtualization: true,
      efficiencyCores: platform === "darwin" ? 4 : 0,
      performanceCores: 4,
    },
    net: [
      {
        ip4: ip,
        ip6: "",
        mac,
        mtu: 1500,
        dhcp: true,
        type: "wired",
        iface: "eth0",
        speed: 1000,
        duplex: "full",
        default: true,
        virtual: false,
        internal: false,
        dnsSuffix: "",
        ifaceName: "Demo Ethernet Adapter",
        ip4subnet: "255.255.255.0",
        ip6subnet: "",
        operstate: "up",
        ieee8021xAuth: "",
        carrierChanges: 0,
        ieee8021xState: "",
      },
    ],
    bios: {
      serial: `DEMO-BIOS-${uuid.slice(0, 4).toUpperCase()}`,
      vendor: "Demo Vendor",
      version: "1.0.0",
      revision: "",
      releaseDate: "2026-01-01",
    },
    uuid: {
      os: uuid,
      macs: [mac],
      hardware: `demo-hardware-${uuid.slice(0, 8)}`,
    },
    system: {
      sku: "DEMO-SKU",
      uuid,
      model: platform === "darwin" ? "Demo Mac" : "Demo PC",
      serial: `DEMO-SERIAL-${uuid.slice(-6).toUpperCase()}`,
      version: "1.0",
      virtual: false,
      manufacturer: "Npcink Demo",
    },
    chassis: {
      sku: "",
      type: "Desktop",
      model: "",
      serial: `DEMO-CHASSIS-${uuid.slice(-4).toUpperCase()}`,
      version: "1.0",
      assetTag: "",
      manufacturer: "Npcink Demo",
    },
    version: "demo",
    graphics: {
      displays: [],
      controllers: [
        {
          bus: "PCI",
          vram: 1024,
          model: "Demo Graphics",
          vendor: "Demo Vendor",
          vramDynamic: true,
        },
      ],
    },
    versions: {},
    baseboard: {
      model: "Demo Board",
      memMax: memoryBytes * 2,
      serial: `DEMO-BOARD-${uuid.slice(-4).toUpperCase()}`,
      version: "1.0",
      assetTag: "",
      memSlots: 2,
      manufacturer: "Npcink Demo",
    },
    memLayout: [
      {
        ecc: false,
        bank: "BANK 0",
        size: memoryBytes,
        type: "DDR4",
        partNum: "DEMO-RAM",
        serialNum: `DEMO-RAM-${uuid.slice(-4).toUpperCase()}`,
        clockSpeed: 2666,
        formFactor: "DIMM",
        voltageMax: 0,
        voltageMin: 0,
        manufacturer: "Demo Memory",
        voltageConfigured: 1.2,
      },
    ],
    diskLayout: [
      {
        name: "Demo SSD",
        size: diskBytes,
        type: "SSD",
        device: "demo0",
        vendor: "Demo Storage",
        serialNum: `DEMO-DISK-${uuid.slice(-4).toUpperCase()}`,
        interfaceType: "NVMe",
        smartStatus: "Ok",
      },
    ],
  });

const data = [
  {
    id: "1",
    name: "演示电脑 A",
    state: "apply",
    number: "1001",
    department: "开发部",
    created_at: "2026-01-10 09:00:00",
    uuid: "demo-device-0001",
    ip: "10.0.0.11",
    purchase: 5200,
    depreciation: 36,
    data: buildDeviceData({
      hostname: "demo-windows-01",
      platform: "Windows",
      osName: "Microsoft Windows 11 Pro",
      cpu: "Intel Core i5 Demo",
      memoryBytes: 16 * 1024 * 1024 * 1024,
      diskBytes: 512 * 1024 * 1024 * 1024,
      ip: "10.0.0.11",
      mac: "02:00:00:00:00:11",
      uuid: "demo-device-0001",
    }),
  },
  {
    id: "2",
    name: "演示电脑 B",
    state: "idie",
    number: "1002",
    department: "运营部",
    created_at: "2026-01-12 10:30:00",
    uuid: "demo-device-0002",
    ip: "10.0.0.12",
    purchase: 6800,
    depreciation: 48,
    data: buildDeviceData({
      hostname: "demo-mac-01",
      platform: "darwin",
      osName: "macOS",
      cpu: "Apple M-series Demo",
      memoryBytes: 8 * 1024 * 1024 * 1024,
      diskBytes: 256 * 1024 * 1024 * 1024,
      ip: "10.0.0.12",
      mac: "02:00:00:00:00:12",
      uuid: "demo-device-0002",
    }),
  },
  {
    id: "3",
    name: "演示电脑 C",
    state: "fault",
    number: "1003",
    department: "推广部",
    created_at: "2026-01-15 14:20:00",
    uuid: "demo-device-0003",
    ip: "10.0.0.13",
    purchase: 4200,
    depreciation: 24,
    data: buildDeviceData({
      hostname: "demo-windows-02",
      platform: "Windows",
      osName: "Microsoft Windows 10 Pro",
      cpu: "Intel Core i3 Demo",
      memoryBytes: 8 * 1024 * 1024 * 1024,
      diskBytes: 256 * 1024 * 1024 * 1024,
      ip: "10.0.0.13",
      mac: "02:00:00:00:00:13",
      uuid: "demo-device-0003",
    }),
  },
];

export default data;
