//主板
export const baseboardData = {
  manufacturer: "Apple Inc.",
  model: "Macmini9,16",
  version: "",
  serial: "C07G47L9Q6NV",
  assetTag: "",
  memMax: 8589934592,
  memSlots: 0,
};

//BIOS
export const biosData = {
  vendor: "Apple Inc.",
  version: "8422.141.2",
  releaseDate: "",
  revision: "",
};

//机箱
export const chassisData = {
  manufacturer: "Apple Inc.",
  model: "Macmini9,1",
  type: "",
  version: "",
  serial: "C07G47L9Q6NV",
  assetTag: "",
  sku: "",
};

//CPU
export const cpuData = {
  manufacturer: "Apple",
  brand: "M1",
  vendor: "Apple",
  family: "458787763",
  model: "",
  stepping: "2",
  revision: "",
  voltage: "",
  speed: 2.4,
  speedMin: 2.4,
  speedMax: 2.4,
  governor: "",
  cores: 8,
  physicalCores: 8,
  performanceCores: 4,
  efficiencyCores: 4,
  processors: 1,
  socket: "SOC",
  flags: "",
  virtualization: true,
  cache: { l1d: 131072, l1i: 65536, l2: 4194304, l3: null },
};

//硬盘
export const diskLayoutData = [
  {
    device: "disk0",
    type: "NVMe",
    name: "APPLE SSD AP0256Q",
    vendor: "Apple",
    size: 251000193024,
    bytesPerSector: null,
    totalCylinders: null,
    totalHeads: null,
    totalSectors: null,
    totalTracks: null,
    tracksPerCylinder: null,
    sectorsPerTrack: null,
    firmwareRevision: "874.140.",
    serialNum: "0ba01609811d421f",
    interfaceType: "PCIe",
    smartStatus: "Ok",
    temperature: null,
  },
];

//显示
export const graphicsDatas = {
  controllers: [
    {
      vendor: "Apple",
      model: "Apple M1",
      bus: "Built-In",
      vramDynamic: true,
      vram: null,
      deviceId: "",
      vendorId: "0x05ac",
      external: false,
      cores: "8",
      metalVersion: "",
    },
    {
      vendor: "Apple",
      model: "Apple M2",
      bus: "Built-In",
      vramDynamic: true,
      vram: null,
      deviceId: "",
      vendorId: "0x05ac",
      external: false,
      cores: "8",
      metalVersion: "",
    },
  ],
  displays: [
    {
      vendor: "",
      vendorId: "61a9",
      model: "Redmi 27 NU",
      productionYear: "2022",
      serial: null,
      displayId: "2",
      main: true,
      builtin: false,
      connection: null,
      sizeX: null,
      sizeY: null,
      pixelDepth: null,
      resolutionX: 3840,
      resolutionY: 2160,
      currentResX: 1920,
      currentResY: 1080,
      positionX: 0,
      positionY: 0,
      currentRefreshRate: 60,
    },
  ],
};

//内存
export const memoryData = [
  {
    size: 8589934592,
    bank: "0",
    type: "LPDDR4",
    ecc: false,
    clockSpeed: 0,
    formFactor: "",
    manufacturer: "Apple",
    partNum: "",
    serialNum: "",
    voltageConfigured: null,
    voltageMin: null,
    voltageMax: null,
  },
  {
    size: 8589934592,
    bank: "0",
    type: "LPDDR5",
    ecc: false,
    clockSpeed: 0,
    formFactor: "",
    manufacturer: "Apple",
    partNum: "",
    serialNum: "",
    voltageConfigured: null,
    voltageMin: null,
    voltageMax: null,
  },
];

//NET
export const netDatas = [
  {
    iface: "lo0",
    ifaceName: "lo0",
    default: false,
    ip4: "127.0.0.1",
    ip4subnet: "255.0.0.0",
    ip6: "::1",
    ip6subnet: "ffff:ffff:ffff:ffff::",
    mac: "",
    internal: true,
    virtual: false,
    operstate: "unknown",
    type: "wired",
    duplex: "full",
    mtu: 16384,
    speed: null,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "anpi0",
    ifaceName: "anpi0",
    default: false,
    ip4: "",
    ip4subnet: "",
    ip6: "fe80::d8b1:99ff:fe04:2962",
    ip6subnet: "ffff:ffff:ffff:ffff::",
    mac: "da:b1:99:04:29:62",
    internal: false,
    virtual: false,
    operstate: "down",
    type: "wired",
    duplex: "full",
    mtu: 1500,
    speed: null,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "anpi1",
    ifaceName: "anpi1",
    default: false,
    ip4: "",
    ip4subnet: "",
    ip6: "fe80::d8b1:99ff:fe04:2963",
    ip6subnet: "ffff:ffff:ffff:ffff::",
    mac: "da:b1:99:04:29:63",
    internal: false,
    virtual: false,
    operstate: "down",
    type: "wired",
    duplex: "full",
    mtu: 1500,
    speed: null,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "en0",
    ifaceName: "en0",
    default: true,
    ip4: "192.168.5.14",
    ip4subnet: "255.255.252.0",
    ip6: "fe80::18c0:250d:2499:e8b8",
    ip6subnet: "ffff:ffff:ffff:ffff::",
    mac: "14:98:77:5a:8d:e5",
    internal: false,
    virtual: false,
    operstate: "up",
    type: "wired",
    duplex: "full",
    mtu: 1500,
    speed: 100,
    dhcp: true,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "en4",
    ifaceName: "en4",
    default: false,
    ip4: "",
    ip4subnet: "",
    ip6: "",
    ip6subnet: "",
    mac: "da:b1:99:04:29:42",
    internal: false,
    virtual: false,
    operstate: "down",
    type: "wired",
    duplex: "full",
    mtu: 1500,
    speed: null,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "en5",
    ifaceName: "en5",
    default: false,
    ip4: "",
    ip4subnet: "",
    ip6: "",
    ip6subnet: "",
    mac: "da:b1:99:04:29:43",
    internal: false,
    virtual: false,
    operstate: "down",
    type: "wired",
    duplex: "full",
    mtu: 1500,
    speed: null,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "en2",
    ifaceName: "en2",
    default: false,
    ip4: "",
    ip4subnet: "",
    ip6: "",
    ip6subnet: "",
    mac: "36:d9:bd:fc:9d:40",
    internal: false,
    virtual: false,
    operstate: "down",
    type: "wired",
    duplex: "full",
    mtu: 1500,
    speed: null,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "en3",
    ifaceName: "en3",
    default: false,
    ip4: "",
    ip4subnet: "",
    ip6: "",
    ip6subnet: "",
    mac: "36:d9:bd:fc:9d:44",
    internal: false,
    virtual: false,
    operstate: "down",
    type: "wired",
    duplex: "full",
    mtu: 1500,
    speed: null,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "ap1",
    ifaceName: "ap1",
    default: false,
    ip4: "",
    ip4subnet: "",
    ip6: "fe80::3498:77ff:fe50:333e",
    ip6subnet: "ffff:ffff:ffff:ffff::",
    mac: "36:98:77:50:33:3e",
    internal: false,
    virtual: false,
    operstate: "down",
    type: "wireless",
    duplex: "full",
    mtu: 1500,
    speed: 10,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "en1",
    ifaceName: "en1",
    default: false,
    ip4: "192.168.0.185",
    ip4subnet: "255.255.255.0",
    ip6: "fe80::484:d31c:fe8:9eea",
    ip6subnet: "ffff:ffff:ffff:ffff::",
    mac: "14:98:77:50:33:3e",
    internal: false,
    virtual: false,
    operstate: "up",
    type: "wireless",
    duplex: "full",
    mtu: 1500,
    speed: 11.75,
    dhcp: true,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "bridge0",
    ifaceName: "bridge0",
    default: false,
    ip4: "",
    ip4subnet: "",
    ip6: "",
    ip6subnet: "",
    mac: "36:d9:bd:fc:9d:40",
    internal: false,
    virtual: false,
    operstate: "down",
    type: "wired",
    duplex: "full",
    mtu: 1500,
    speed: null,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "awdl0",
    ifaceName: "awdl0",
    default: false,
    ip4: "",
    ip4subnet: "",
    ip6: "fe80::f467:22ff:fee7:2d7d",
    ip6subnet: "ffff:ffff:ffff:ffff::",
    mac: "f6:67:22:e7:2d:7d",
    internal: false,
    virtual: false,
    operstate: "up",
    type: "wireless",
    duplex: "full",
    mtu: 1500,
    speed: 10,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "llw0",
    ifaceName: "llw0",
    default: false,
    ip4: "",
    ip4subnet: "",
    ip6: "fe80::f467:22ff:fee7:2d7d",
    ip6subnet: "ffff:ffff:ffff:ffff::",
    mac: "f6:67:22:e7:2d:7d",
    internal: false,
    virtual: false,
    operstate: "down",
    type: "wireless",
    duplex: "full",
    mtu: 1500,
    speed: null,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "utun0",
    ifaceName: "utun0",
    default: false,
    ip4: "",
    ip4subnet: "",
    ip6: "fe80::d7fe:fe45:af6f:cbdf",
    ip6subnet: "ffff:ffff:ffff:ffff::",
    mac: "",
    internal: false,
    virtual: false,
    operstate: "unknown",
    type: "wired",
    duplex: "full",
    mtu: 1380,
    speed: null,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "utun1",
    ifaceName: "utun1",
    default: false,
    ip4: "",
    ip4subnet: "",
    ip6: "fe80::e4d0:e158:1ba0:b65a",
    ip6subnet: "ffff:ffff:ffff:ffff::",
    mac: "",
    internal: false,
    virtual: false,
    operstate: "unknown",
    type: "wired",
    duplex: "full",
    mtu: 2000,
    speed: null,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
  {
    iface: "utun2",
    ifaceName: "utun2",
    default: false,
    ip4: "",
    ip4subnet: "",
    ip6: "fe80::ce81:b1c:bd2c:69e",
    ip6subnet: "ffff:ffff:ffff:ffff::",
    mac: "",
    internal: false,
    virtual: false,
    operstate: "unknown",
    type: "wired",
    duplex: "full",
    mtu: 1000,
    speed: null,
    dhcp: false,
    dnsSuffix: "",
    ieee8021xAuth: "",
    ieee8021xState: "",
    carrierChanges: 0,
  },
];

//OS
export const osDatas = {
  platform: "darwin",
  distro: "macOS",
  release: "13.5.1",
  codename: "macOS Ventura",
  kernel: "22.6.0",
  arch: "arm64",
  hostname: "muzedeMac-mini-2.local",
  fqdn: "muzedeMac-mini-2.local",
  codepage: "UTF-8",
  logofile: "darwin",
  serial: "CE831117-201E-35F6-A293-FCC0F02097A3",
  build: "22G90",
  servicepack: "",
  uefi: true,
};

//系统
export const systemData = {
  manufacturer: "Apple Inc.",
  model: "Macmini9,1",
  version: "",
  serial: "C07G47L9Q6NV",
  uuid: "34d333cc-da7b-5bf8-9d73-6c08d0fb05b3",
  sku: "",
  virtual: false,
};

//uuid
export const uuidDatas = {
  os: "34d333cc-da7b-5bf8-9d73-6c08d0fb05b3",
  hardware: "C07G47L9Q6NV-2",
  macs: [
    "14:98:77:50:33:3e",
    "14:98:77:5a:8d:e5",
    "36:98:77:50:33:3e",
    "da:b1:99:04:29:62",
    "da:b1:99:04:29:63",
    "f6:67:22:e7:2d:7d",
  ],
};

//version
export const version = "5.21.4";

//versions
export const versions = {
  kernel: "22.6.0",
  openssl: "1.1.1",
  systemOpenssl: "3.3.6",
  systemOpensslLib: "LibreSSL",
  node: "18.16.1",
  v8: "11.6.189.18-electron.0",
  npm: "9.7.2",
  yarn: "",
  pm2: "",
  gulp: "",
  grunt: "",
  git: "2.39.2",
  tsc: "4.9.5",
  mysql: "5.7.39",
  redis: "",
  mongodb: "6.0.5",
  apache: "2.4.56",
  nginx: "1.23.3",
  php: "7.4.32",
  docker: "20.10.22",
  postfix: "3.2.2",
  postgresql: "",
  perl: "5.30.3",
  python: "",
  python3: "3.9.6",
  pip: "",
  pip3: "21.2.4",
  java: "",
  gcc: "14.0.3",
  virtualbox: "",
  bash: "3.2.57",
  zsh: "5.9",
  fish: "",
  powershell: "",
  dotnet: "",
};

export const dataOne = {
  baseboard: baseboardData, //主板
  bios: biosData, //BIOS
  chassis: chassisData, //机箱
  cpu: cpuData, //CPU
  diskLayout: diskLayoutData, //硬盘
  graphics: graphicsDatas, //显示
  memLayout: memoryData, //内存
  net: netDatas, //网络
  os: osDatas, //OS
  system: systemData, //系统
  uuid: uuidDatas, //UUID
  version: version, //版本
  versions: versions, //版本信息
};
export const dataTwo = {
  version: "5.21.4",
  system: {
    manufacturer: "Dell Inc.",
    model: "Vostro 3690",
    version: "",
    serial: "CN0TSH3",
    uuid: "4c4c4544-004e-3010-8054-c3c04f534833",
    sku: "0A50",
    virtual: false,
  },
  bios: {
    vendor: "Dell Inc.",
    version: "1.5.0",
    releaseDate: "2022-02-11",
    revision: "",
    serial: "CN0TSH3",
  },
  baseboard: {
    manufacturer: "Dell Inc.",
    model: "0MJF5P",
    version: "A00",
    serial: "/CN0TSH3/CNFCW0017M02IF/",
    assetTag: "",
    memMax: 68719476736,
    memSlots: 2,
  },
  chassis: {
    manufacturer: "Dell Inc.",
    model: "",
    type: "Desktop",
    version: "",
    serial: "CN0TSH3",
    assetTag: "",
    sku: "",
  },
  os: {
    platform: "Windows",
    distro: "Microsoft Windows 11 家庭版",
    release: "10.0.22621",
    codename: "",
    kernel: "10.0.22621",
    arch: "ia32",
    hostname: "DESKTOP-UFCMBUD",
    fqdn: "DESKTOP-UFCMBUD",
    codepage: "936",
    logofile: "windows",
    serial: "00326-10000-00000-AA468",
    build: "22621",
    servicepack: "0.0",
    uefi: true,
    hypervisor: false,
    remoteSession: false,
  },
  uuid: {
    os: "109604ce-bb3b-451a-82ff-437ba485f610",
    hardware: "4c4c4544-004e-3010-8054-c3c04f534833",
    macs: ["d0:8e:79:07:a8:60"],
  },
  versions: {
    kernel: "10.0.22621",
    openssl: "1.1.1",
    systemOpenssl: "",
    systemOpensslLib: "",
    node: "18.16.1",
    v8: "11.6.189.20-electron.0",
    npm: "",
    yarn: "",
    pm2: "",
    gulp: "",
    grunt: "",
    git: "",
    tsc: "",
    mysql: "",
    redis: "",
    mongodb: "",
    apache: "",
    nginx: "",
    php: "",
    docker: "",
    postfix: "",
    postgresql: "",
    perl: "",
    python: "",
    python3: "",
    pip: "",
    pip3: "",
    java: "",
    gcc: "",
    virtualbox: "",
    bash: "",
    zsh: "",
    fish: "",
    powershell: "5.1.22621.1778:",
    dotnet: "4.8.09032",
  },
  cpu: {
    manufacturer: "Intel",
    brand: "Core™ i3-10105",
    vendor: "GenuineIntel",
    family: "6",
    model: "165",
    stepping: "3",
    revision: "",
    voltage: "",
    speed: 3.7,
    speedMin: 3.7,
    speedMax: 3.7,
    governor: "",
    cores: 8,
    physicalCores: 4,
    performanceCores: 8,
    efficiencyCores: 0,
    processors: 1,
    socket: "LGA1200",
    flags:
      "de pse tsc msr mce sep mtrr mca cmov psn clfsh ds acpi mmx fxsr sse sse2 ss htt tm ia64 pbe",
    virtualization: false,
    cache: { l1d: 0, l1i: 0, l2: 1048576, l3: 6291456 },
  },
  graphics: {
    controllers: [
      {
        vendor: "Intel Corporation",
        model: "Intel(R) UHD Graphics 630",
        bus: "PCI",
        vram: 1024,
        vramDynamic: true,
        subDeviceId: "0A501028",
      },
    ],
    displays: [
      {
        vendor: "(标准监视器类型)",
        model: "通用即插即用监视器",
        deviceName: "\\\\.\\DISPLAY1",
        main: true,
        builtin: false,
        connection: "DP",
        resolutionX: 1920,
        resolutionY: 1080,
        sizeX: 53,
        sizeY: 30,
        pixelDepth: 32,
        currentResX: 1920,
        currentResY: 1080,
        positionX: 0,
        positionY: 0,
        currentRefreshRate: 60,
      },
    ],
  },
  net: [
    {
      iface: "以太网",
      ifaceName: "Realtek PCIe GbE Family Controller",
      default: true,
      ip4: "192.168.21.15",
      ip4subnet: "255.255.252.0",
      ip6: "fe80::ba10:c41e:65ca:1c13",
      ip6subnet: "ffff:ffff:ffff:ffff::",
      mac: "d0:8e:79:07:a8:60",
      internal: false,
      virtual: false,
      operstate: "up",
      type: "wired",
      duplex: "",
      mtu: "",
      speed: 100,
      dhcp: true,
      dnsSuffix: "",
      ieee8021xAuth: "Unknown",
      ieee8021xState: "Unknown",
      carrierChanges: 0,
    },
    {
      iface: "Loopback Pseudo-Interface 1",
      ifaceName: "Loopback Pseudo-Interface 1",
      default: false,
      ip4: "127.0.0.1",
      ip4subnet: "255.0.0.0",
      ip6: "::1",
      ip6subnet: "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
      mac: "00:00:00:00:00:00",
      internal: true,
      virtual: false,
      operstate: "down",
      type: "",
      duplex: "",
      mtu: "",
      speed: null,
      dhcp: false,
      dnsSuffix: "",
      ieee8021xAuth: "Unknown",
      ieee8021xState: "Unknown",
      carrierChanges: 0,
    },
    {
      iface: "WLAN",
      ifaceName: "Qualcomm QCA9377 802.11ac Wireless Adapter",
      default: false,
      ip4: "",
      ip4subnet: "",
      ip6: "",
      ip6subnet: "",
      mac: "f8:89:d2:c9:8d:11",
      virtual: false,
      operstate: "down",
      type: "wireless",
      duplex: "",
      mtu: "",
      speed: 9223372036854.775,
      dhcp: true,
      dnsSuffix: "",
      ieee8021xAuth: "Unknown",
      ieee8021xState: "Unknown",
      carrierChanges: 0,
    },
    {
      iface: "蓝牙网络连接",
      ifaceName: "Bluetooth Device (Personal Area Network)",
      default: false,
      ip4: "",
      ip4subnet: "",
      ip6: "",
      ip6subnet: "",
      mac: "f8:89:d2:c9:8d:12",
      virtual: false,
      operstate: "down",
      type: "wired",
      duplex: "",
      mtu: "",
      speed: 3,
      dhcp: true,
      dnsSuffix: "",
      ieee8021xAuth: "Unknown",
      ieee8021xState: "Unknown",
      carrierChanges: 0,
    },
  ],
  memLayout: [
    {
      size: 17179869184,
      bank: "",
      type: "DDR4",
      ecc: false,
      clockSpeed: 2667,
      formFactor: "DIMM",
      manufacturer: "80AD000080AD",
      partNum: "HMAA2GU6CJR8N-XN",
      serialNum: "45C0ECAF",
      voltageConfigured: 1.2,
      voltageMin: 0,
      voltageMax: 0,
    },
  ],
  diskLayout: [
    {
      device: "\\\\.\\PHYSICALDRIVE1",
      type: "SSD",
      name: "KBG40ZNS256G NVMe KIOXIA 256GB",
      vendor: "",
      size: 256052966400,
      bytesPerSector: 512,
      totalCylinders: 31130,
      totalHeads: 255,
      totalSectors: 500103450,
      totalTracks: 7938150,
      tracksPerCylinder: 255,
      sectorsPerTrack: 63,
      firmwareRevision: "10410106",
      serialNum: "0100_0000_0000_0000_8CE3_8E04_02A4_9E40.",
      interfaceType: "NVMe",
      smartStatus: "Ok",
      temperature: null,
    },
    {
      device: "\\\\.\\PHYSICALDRIVE0",
      type: "HD",
      name: "ST1000DM010-2EP102",
      vendor: "Seagate",
      size: 1000202273280,
      bytesPerSector: 512,
      totalCylinders: 121601,
      totalHeads: 255,
      totalSectors: 1953520065,
      totalTracks: 31008255,
      tracksPerCylinder: 255,
      sectorsPerTrack: 63,
      firmwareRevision: "1001",
      serialNum: "ZN1QH14C",
      interfaceType: "SATA",
      smartStatus: "Ok",
      temperature: null,
    },
  ],
};

export const dataThree = {
  version: "5.21.4",
  system: {
    manufacturer: "Colorful Technology And Development Co.,LTD",
    model: "BATTLE-AX B760M-F PRO",
    version: "Default string",
    serial: "Default string",
    uuid: "03000200-0400-0500-0006-000700080009",
    sku: "Default string",
    virtual: false,
  },
  bios: {
    vendor: "American Megatrends International, LLC.",
    version: "5.27",
    releaseDate: "2023-02-15",
    revision: "",
    serial: "Default string",
  },
  baseboard: {
    manufacturer: "Colorful Technology And Development Co.,LTD",
    model: "BATTLE-AX B760M-F PRO",
    version: "V20",
    serial: "Default string",
    assetTag: "",
    memMax: 137438953472,
    memSlots: 4,
  },
  chassis: {
    manufacturer: "Default string",
    model: "",
    type: "Desktop",
    version: "Default string",
    serial: "Default string",
    assetTag: "",
    sku: "",
  },
  os: {
    platform: "Windows",
    distro: "Microsoft Windows 11 家庭版",
    release: "10.0.22621",
    codename: "",
    kernel: "10.0.22621",
    arch: "ia32",
    hostname: "DESKTOP-V1ADGBA",
    fqdn: "DESKTOP-V1ADGBA",
    codepage: "936",
    logofile: "windows",
    serial: "00326-10000-00000-AA964",
    build: "22621",
    servicepack: "0.0",
    uefi: true,
    hypervisor: false,
    remoteSession: false,
  },
  uuid: {
    os: "899a44f2-7bd9-43b1-9a03-7ae7247cc439",
    hardware: "03000200-0400-0500-0006-000700080009",
    macs: ["00:e0:4c:5a:d3:54"],
  },
  versions: {
    kernel: "10.0.22621",
    openssl: "1.1.1",
    systemOpenssl: "",
    systemOpensslLib: "",
    node: "18.16.1",
    v8: "11.6.189.20-electron.0",
    npm: "",
    yarn: "",
    pm2: "",
    gulp: "",
    grunt: "",
    git: "",
    tsc: "",
    mysql: "",
    redis: "",
    mongodb: "",
    apache: "",
    nginx: "",
    php: "",
    docker: "",
    postfix: "",
    postgresql: "",
    perl: "",
    python: "",
    python3: "",
    pip: "",
    pip3: "",
    java: "",
    gcc: "",
    virtualbox: "",
    bash: "",
    zsh: "",
    fish: "",
    powershell: "5.1.22621.1778:",
    dotnet: "4.8.09032",
  },
  cpu: {
    manufacturer: "Intel",
    brand: "Gen Intel® Core™ i5-12400",
    vendor: "GenuineIntel",
    family: "6",
    model: "151",
    stepping: "5",
    revision: "",
    voltage: "",
    speed: 2.5,
    speedMin: 2.5,
    speedMax: 2.5,
    governor: "",
    cores: 12,
    physicalCores: 6,
    performanceCores: 12,
    efficiencyCores: 0,
    processors: 1,
    socket: "Other",
    flags:
      "de pse tsc msr mce sep mtrr mca cmov psn clfsh ds acpi mmx fxsr sse sse2 ss htt tm ia64 pbe",
    virtualization: false,
    cache: {
      l1d: 294912,
      l1i: 196608,
      l2: 7864320,
      l3: 18874368,
    },
  },
  graphics: {
    controllers: [
      {
        vendor: "Intel Corporation",
        model: "Intel(R) UHD Graphics 730",
        bus: "PCI",
        vram: 1024,
        vramDynamic: true,
        subDeviceId: "00000000",
      },
    ],
    displays: [
      {
        vendor: "(标准监视器类型)",
        model: "通用即插即用监视器",
        deviceName: "\\\\.\\DISPLAY1",
        main: true,
        builtin: false,
        connection: "HDMI",
        resolutionX: 1920,
        resolutionY: 1080,
        sizeX: 60,
        sizeY: 33,
        pixelDepth: 32,
        currentResX: 1920,
        currentResY: 1080,
        positionX: 0,
        positionY: 0,
        currentRefreshRate: 60,
      },
    ],
  },
  net: [
    {
      iface: "以太网",
      ifaceName: "Realtek PCIe GbE Family Controller",
      default: true,
      ip4: "192.168.21.26",
      ip4subnet: "255.255.252.0",
      ip6: "fe80::c6d2:5820:394d:9a8",
      ip6subnet: "ffff:ffff:ffff:ffff::",
      mac: "00:e0:4c:5a:d3:54",
      internal: false,
      virtual: false,
      operstate: "up",
      type: "wired",
      duplex: "",
      mtu: "",
      speed: 100,
      dhcp: true,
      dnsSuffix: "",
      ieee8021xAuth: "Unknown",
      ieee8021xState: "Unknown",
      carrierChanges: 0,
    },
    {
      iface: "Loopback Pseudo-Interface 1",
      ifaceName: "Loopback Pseudo-Interface 1",
      default: false,
      ip4: "127.0.0.1",
      ip4subnet: "255.0.0.0",
      ip6: "::1",
      ip6subnet: "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
      mac: "00:00:00:00:00:00",
      internal: true,
      virtual: false,
      operstate: "down",
      type: "",
      duplex: "",
      mtu: "",
      speed: null,
      dhcp: false,
      dnsSuffix: "",
      ieee8021xAuth: "Unknown",
      ieee8021xState: "Unknown",
      carrierChanges: 0,
    },
  ],
  memLayout: [
    {
      size: 17179869184,
      bank: "BANK 0",
      type: "DDR4",
      ecc: false,
      clockSpeed: 3200,
      formFactor: "DIMM",
      manufacturer: "Colorful Technology Ltd",
      partNum: "CD16G3200D4NZ22",
      serialNum: "4F757DE1",
      voltageConfigured: 1.2,
      voltageMin: 1.2,
      voltageMax: 1.2,
    },
  ],
  diskLayout: [
    {
      device: "\\\\.\\PHYSICALDRIVE0",
      type: "SSD",
      name: "CF500 256GB",
      vendor: "",
      size: 256052966400,
      bytesPerSector: 512,
      totalCylinders: 31130,
      totalHeads: 255,
      totalSectors: 500103450,
      totalTracks: 7938150,
      tracksPerCylinder: 255,
      sectorsPerTrack: 63,
      firmwareRevision: "HT3130A2",
      serialNum: "2023050707080",
      interfaceType: "SATA",
      smartStatus: "Ok",
      temperature: null,
    },
  ],
};
